openapi: 3.0.0
info:
  description: Inventory API for a Healthcare System
  version: "1.0.0"
  title: Dental Cura API
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/fr3m3n/DentalCura/1.0.0
  - url: https://api.example.com/v1

tags:
  - name: patient
    description: Operations related to patients and their information
  - name: dentist
    description: Operations related to dentists and their services
  - name: appointment
    description: Operations related to appointments scheduling and management
  - name: user
    description: Operations related to user authentication and management

paths:
  /patient:
    get:
      tags:
        - patient
      summary: Get a list of patients
      responses:
        '200':
          description: List of patients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
    post:
      tags:
        - patient
      summary: Create a new patient
      requestBody:
        description: Patient details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        '201':
          description: Patient created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
  /patient/{id}:
    get:
      tags:
        - patient
      summary: Get patient details by ID
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the patient
      responses:
        '200':
          description: Patient details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
    put:
      tags:
        - patient
      summary: Update patient details
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the patient
      requestBody:
        description: Updated patient details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        '200':
          description: Patient details updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
    delete:
      tags:
        - patient
      summary: Delete a patient
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the patient
      responses:
        '204':
          description: Patient deleted successfully

  /dentist:
    get:
      tags:
        - dentist
      summary: Get a list of dentists
      responses:
        '200':
          description: List of dentists
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dentist'
    post:
      tags:
        - dentist
      summary: Create a new dentist
      requestBody:
        description: Dentist details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dentist'
      responses:
        '201':
          description: Dentist created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dentist'
  /dentist/{id}:
    get:
      tags:
        - dentist
      summary: Get dentist details by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the dentist
      responses:
        '200':
          description: Dentist details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dentist'
    put:
      tags:
        - dentist
      summary: Update dentist details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the dentist
      requestBody:
        description: Updated dentist details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dentist'
      responses:
        '200':
          description: Dentist details updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dentist'
    delete:
      tags:
        - dentist
      summary: Delete a dentist
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the dentist
      responses:
        '204':
          description: Dentist deleted successfully

  /appointment:
    get:
      tags:
        - appointment
      summary: Get a list of appointments
      responses:
        '200':
          description: List of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
    post:
      tags:
        - appointment
      summary: Create a new appointment
      requestBody:
        description: Appointment details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '201':
          description: Appointment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
  /appointment/{id}:
    get:
      tags:
        - appointment
      summary: Get appointment details by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the appointment
      responses:
        '200':
          description: Appointment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
    put:
      tags:
        - appointment
      summary: Update appointment details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the appointment
      requestBody:
        description: Updated appointment details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '200':
          description: Appointment details updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
    delete:
      tags:
        - appointment
      summary: Delete a appointment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the appointment
      responses:
        '204':
          description: Appointment deleted successfully

  /user:
    get:
      tags:
        - user
      summary: Get a list of users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
        - user
      summary: Create a new user
      requestBody:
        description: User details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /user/{id}:
    get:
      tags:
        - user
      summary: Get user details by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags:
        - user
      summary: Update user details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user
      requestBody:
        description: Updated user details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User details updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      tags:
        - user
      summary: Delete a user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user
      responses:
        '204':
          description: User deleted successfully


components:
    schemas:
    Schema:
      type: object
      properties:
        id:
          type: integer
          format: int64